[package]
name = "rust_decimal"
version = "1.7.0"
authors = ["Paul Mason <paul@form1.co.nz>"]
edition = "2018"
description = "A Decimal Implementation written in pure Rust suitable for financial calculations."
documentation = "https://docs.rs/rust_decimal/"
repository = "https://github.com/paupino/rust-decimal"
readme = "./README.md"
keywords = ["decimal","financial","fixed","precision"]
categories = ["science","data-structures"]
license = "MIT"

[dependencies]
num-traits = { default-features = false, version = "0.2" }
byteorder = { default-features = false, version = "1.3", optional = true }
bytes = { default-features = false, version = "0.5", optional = true }
diesel = { version = "1.4", default-features = false, features = ["postgres"], optional = true }
postgres = { default-features = false, version = "0.17", optional = true }
tokio-postgres = { default-features = false, version = "0.5", optional = true }
serde = { default-features = false, version = "1.0", optional = true }

[dev-dependencies]
bincode = "1.3"
bytes = "0.5"
futures = "0.3"
rand = "0.7"
serde_json = "1.0"
serde_derive = "1.0"
tokio = { version = "0.2", features = ["rt-threaded", "test-util", "macros"] }

[features]
std = []
default = ["serde"]
db-postgres = ["postgres", "bytes", "byteorder", "std"]
db-tokio-postgres = ["postgres", "tokio-postgres", "bytes", "byteorder", "std"]
db-diesel-postgres = ["diesel", "std"]
serde-bincode = ["serde"]
serde-float = ["serde"]
tokio-pg = ["db-tokio-postgres"] # Backwards compatability

[workspace]
members = [".", "./macros", "./fuzzer"]
